name: atlas_env
channels:
    - bioconda
    - brwnj
dependencies:
    - python=3.5
    - bbmap
    - click
    - diamond
    - brwnj::maxbin2
    - megahit
    - pandas
    - prodigal
    - pyyaml
    - samtools
    - snakemake
    - spades
    - verse
