name: atlas_env
channels:
    - bioconda
dependencies:
    - bbmap
    - click
    - diamond
    - maxbin2
    - megahit
    - pandas
    - prodigal
    - pyyaml
    - samtools
    - snakemake
    - spades
    - verse

# python 3.5 with pandas, sqlite3
