name: atlas_env
channels:
    - bioconda
    - r
    - defaults
    - conda-forge
dependencies:
    - python=3.5
    - bbmap
    - click
    - diamond
    - maxbin2
    - megahit
    - pandas
    - prodigal
    - pyyaml
    - samtools
    - snakemake
    - spades
    - subread
    - pip:
        - pnnl-atlas
