defaults: &defaults
  docker:
    - image: continuumio/miniconda3
  environment:
    DATABASE_DIR: /databases
    WORKING_DIR: .test/Dryrun
    N_THREADS: 4
    MEM: 4

version: 2

jobs:
  build:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout
      - run: pwd
      - run:
          name: Setup conda
          command: |
           conda config --add channels bioconda
           conda config --add channels conda-forge
           conda config --set always_yes true
           conda create -p /atlasenv
      - restore_cache:
          key: atlasenv-dependencies-{{ checksum "atlasenv.yml" }}
      - run:
          name: install dependencies
          command:  conda env update -p /atlasenv --file atlasenv.yml
      - save_cache:
          key: atlasenv-dependencies-{{ checksum "atlasenv.yml" }}
          paths:
            - "/atlasenv"
      - run:
          name: Install atlas
          command: |
              source activate /atlasenv
              python setup.py install
              conda list
              atlas --help
              atlas --version
      - run:
          name: short test
          command: |
              source activate /atlasenv
              atlas --help
              atlas --version
      - run: |
            source activate /atlasenv
            atlas download --db-dir $DATABASE_DIR -n
      - run:
          name: Init
          command: |
              source activate /atlasenv
              atlas init --db-dir $DATABASE_DIR --threads 3 -w  $WORKING_DIR .test/reads/empty
      - run:
          name: Dryrun
          command: |
              source activate /atlasenv
              atlas run -w $WORKING_DIR --dryrun $@

      - restore_cache:
          key: conda-envs-{{ tar -c atlas/envs | checksum  }}
      - run:
          name: install environements
          command: |
              source activate /atlasenv
              atlas run all -w $WORKING_DIR --create-envs-only
              atlas run None -w $WORKING_DIR logs/checkm_init.txt
      - save_cache:
          key: conda-envs-{{ tar -c atlas/envs | checksum  }}
          paths:
            - $DATABASE_DIR
      - persist_to_workspace:
          root: /
          paths:
            - atlasenv
            - databases
            - root/project



#      - run: .test/test_assembly.sh




workflows:
  version: 2
  build_and_test:
    jobs:
      - build
