defaults: &defaults
  docker:
    - image: continuumio/miniconda3
  environment:
    DATABASE_DIR: databases
    WORKING_DIR: WD
    N_THREADS: 4

version: 2

jobs:
  build:
    <<: *defaults
    parallelism: 4
    steps:
      - checkout
      - run: conda config --add channels conda-forge
      - run: conda config --add channels bioconda
      - run: conda config --set always_yes true
      - run: conda config --set quiet true
      - run: conda install python>=3.6 snakemake pandas bbmap=37.78 click ruamel.yaml biopython
      - run: pip install .
      - run: atlas --help
      - run: atlas --version
      - run: atlas run --help
      # make config
      - run: ls example_data
      - run: atlas init --db-dir $DATABASE_DIR --threads $N_THREADS --assembler spades example_data
      # dryrun
      - run: atlas download --db-dir $DATABASE_DIR --dryrun
      - run: atlas run qc --dryrun
      - run: atlas run assemble --dryrun
      - run: atlas run genomes --dryrun
      - run: atlas run genecatalog --dryrun
      - run: atlas run --dryrun
      - run: atlas run qc
      - run: atlas run assemble
#      - run: atlas run

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
