defaults: &defaults
  docker:
    - image: continuumio/miniconda3
  environment:
    DATABASE_DIR: .test/databases
    WORKING_DIR: .test/Dryrun
    N_THREADS: 4
    MEM: 4

version: 2

jobs:
  build:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          key: atlasenv-{{ checksum "atlasenv.yml" }}
      - run:
          name: Setup conda
          command: |
           conda config --add channels bioconda
           conda config --add channels conda-forge
           conda config --set always_yes true
           conda init bash
      - run:
          name: install dependencies
          command:  conda env create -p path_atlasenv --file atlasenv.yml
      - save_cache:
          key: atlasenv-{{ checksum "atlasenv.yml" }}
          paths:
            - "path_atlasenv"
      - run: python setup.py install
      - run:
          name: test if exists
          command: |
              source activate -p path_atlasenv
              conda list
              atlas --help
              atlas --version
      - run:
          name: Dryrun
          command: |
              source activate -p path_atlasenv
              .test/dryrun.sh
      - restore_cache:
          key: conda-envs-{{ tar -c atlas/envs | checksum  }}
      - run:
          name: install environements
          command: |
              source activate -p path_atlasenv
              atlas run all -w $WORKING_DIR --create-envs-only
              atlas run None -w $WORKING_DIR logs/checkm_init.txt
      - save_cache:
          key: conda-envs-{{ tar -c atlas/envs | checksum  }}
          paths:
            - DATABASE_DIR

#      - run: .test/test_assembly.sh




workflows:
  version: 2
  build_and_test:
    jobs:
      - build
