defaults: &defaults
  docker:
    - image: continuumio/miniconda3


version: 2

jobs:
  install:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: conda config --add channels conda-forge
      - run: conda config --add channels bioconda
      - run: conda config --set always_yes true
      - run: conda config --set quiet true
      - run: conda install python>=3.6 snakemake pandas bbmap=37.78 click ruamel.yaml biopython





workflows:
  version: 2
  build_and_test:
    jobs:
      - install
