defaults: &defaults
  docker:
    - image: continuumio/miniconda3
  environment:
    DATABASE_DIR: .test/databases
    WORKING_DIR: .test/Dryrun
    N_THREADS: 4
    MEM: 4

version: 2

jobs:
  build:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout
      - run: conda config --add channels bioconda
      - run: conda config --add channels conda-forge
      - run: conda config --set always_yes true
      - run: conda env update --file atlasenv.yml
      - run: python setup.py install
      - run: conda list
      - run: atlas --help
      - run: atlas --version
      # make config
      - run: .test/dryrun.sh
      - run: atlas run all -w $WORKING_DIR --create-envs-only
      - run: atlas run None -w $WORKING_DIR logs/checkm_init.txt
      - run: .test/test_assembly.sh



workflows:
  version: 2
  build_and_test:
    jobs:
      - build
