phred_offset: 33
filtering:
    threads: 4
    # fastas to parse into kmers which are then trimmed from the sequences
    adapters: ref/phix174_ill.ref.fa.gz,ref/adapters.fa.gz
    # lower than 20 to allow overlap the chance to increase the quality
    minimum_base_quality: 10
    # kmer mismatches allowed during adapter trim process
    allowable_kmer_mismatches: 1
    # length of kmer to search against sequences
    reference_kmer_match_length: 31
    # passing single-end read length, prior to merging
    minimum_passing_read_length: 51
    # after merging; the allowable limit of erroneous bases; accepts fractions as well
    maximum_expected_error: 1
merging:
    threads: 4
    minimum_overlap: 10
    maximum_overlap: 150
    maximum_mismatch_density: 0.25
contamination_filtering:
    threads: 12
    # fastas placed into ref/contamination_references, list their file names
    # omitting the path
    references: adapter.fa

# Megahit parameters
# megahit:max_mem 0.99
# megahit:length_of_library_insert 250
# megahit:kmer_min 21
# megahit:kmer_max 121
